GET http://localhost:8080/api/usuarios
###
POST http://localhost:8080/api/usuarios

###
PUT http://localhost:8080/api/usuarios


###
DELETE  http://localhost:8080/api/usuarios
###
PATCH  http://localhost:8080/api/usuarios
